#!/bin/bash
# WealthForge - Log Unsuccessful Deployments
# Usage: ./scripts/log-deployment-failure.sh "vercel" "build-failed-404" "error-details-here"

set -euo pipefail

DEPLOY_TARGET=$1:-"unknown"
FAILURE_TYPE=$2:-"unknown"
ERROR_DETAILS=$3:-"No details provided"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
LOG_DIR="deployment-logs"
LOG_FILE="${LOG_DIR}/${DEPLOY_TARGET}-${FAILURE_TYPE}-${TIMESTAMP}.md"

mkdir -p "$LOG_DIR"

cat > "$LOG_FILE" << EOF
# Deployment Failure Log

**Date**: $(date)
**Target**: $DEPLOY_TARGET
**Failure Type**: $FAILURE_TYPE
**Branch**: $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
**Commit**: $(git rev-parse HEAD 2>/dev/null || echo "unknown")

## Error Details
$ERROR_DETAILS

## Recommended Next Steps
- Check environment variables (Paystack, Stripe, DATABASE_URL)
- Verify build locally with `npm run build`
- Check Vercel build logs for specific module errors
- For 404s: Review next.config.js, route casing, and trailing slashes
- For ArgoCD: Check image tags and force sync

## Reproduction Steps
1. 
2. 

---
*Auto-generated by Wealth OS deployment logger*
EOF

echo "✅ Failure logged to: $LOG_FILE"

# Optional: Auto-commit the log (uncomment if desired)
# git add "$LOG_FILE"
# git commit -m "chore: Log deployment failure - $DEPLOY_TARGET $FAILURE_TYPE $TIMESTAMP"
# git push