#!/bin/bash
# WealthForge - Log ArgoCD / Kubernetes Deployment Failures
# Usage:
#   ./scripts/log-argocd-failure.sh "sync-failed" "ImagePullBackOff on wealthforge-web"
#   AUTO_COMMIT=true ./scripts/log-argocd-failure.sh "rollout-failed" "CrashLoopBackOff"

set -euo pipefail

FAILURE_TYPE=${1:-"argocd-failure"}
ERROR_DETAILS=${2:-"No details provided"}
AUTO_COMMIT=${AUTO_COMMIT:-false}
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
LOG_DIR="deployment-logs"
LOG_FILE="${LOG_DIR}/argocd-${FAILURE_TYPE}-${TIMESTAMP}.md"

mkdir -p "$LOG_DIR"

# Try to get current ArgoCD app status if available
ARGOCD_STATUS=""
if command -v argocd &> /dev/null && [ -n "${ARGOCD_APP:-}" ]; then
  ARGOCD_STATUS=$(argocd app get "$ARGOCD_APP" --output json 2>/dev/null || echo "Could not fetch ArgoCD status")
fi

cat > "$LOG_FILE" << EOF
# ArgoCD / Kubernetes Deployment Failure Log

**Date**: $(date)
**Failure Type**: $FAILURE_TYPE
**Branch**: $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
**Commit**: $(git rev-parse HEAD 2>/dev/null || echo "unknown")

## Error Details
$ERROR_DETAILS

## ArgoCD Application Status (if available)
```json
$ARGOCD_STATUS
```

## Common ArgoCD/Kubernetes Issues & Fixes
- **ImagePullBackOff**: Check image tag in Helm values and registry access
- **CrashLoopBackOff**: Check pod logs (`kubectl logs -l app=wealthforge-web`)
- **Sync failed**: Review ArgoCD UI for resource errors or Helm template issues
- **Rollout stalled**: Check ReplicaSet and pod status
- **Config/Secret issues**: Verify SealedSecrets or environment variables in Helm

## Recommended Commands
```bash
# View recent ArgoCD application events
argocd app get $ARGOCD_APP

# Check pod logs
kubectl logs -l app=wealthforge-web --tail=100

# Force sync in ArgoCD
argocd app sync $ARGOCD_APP --prune
```

---
*Auto-generated by Wealth OS ArgoCD failure logger*
EOF

echo "✅ ArgoCD failure logged to: $LOG_FILE"

if [ "$AUTO_COMMIT" = true ]; then
  echo "📦 Auto-committing ArgoCD failure log..."
  git add "$LOG_FILE"
  git commit -m "chore: Log ArgoCD/K8s failure - $FAILURE_TYPE $TIMESTAMP"
  git push origin "$(git rev-parse --abbrev-ref HEAD)"
  echo "✅ ArgoCD failure log committed and pushed."
fi